-- Camera authoring — wraps Defold's camera component + common follow rigs.
-- Generates the .go (with embedded camera) plus the optional follow .script
-- in a single call. Inspired by godot-ai's camera_manage.

local util = require "mcp.lib.util"
local gameobject = require "mcp.handlers.gameobject"

local M = {}

-- ---------------------------------------------------------- helpers ----

-- Format a Defold camera component's `data` proto-text block.
-- All numbers serialize as plain floats; enum-ish fields stay as ints.
local function _camera_component_data(opts)
  opts = opts or {}
  local lines = {
    "aspect_ratio: " .. tostring(opts.aspect_ratio or 1.0),
    "fov: "          .. tostring(opts.fov or 1.2566),
    "near_z: "       .. tostring(opts.near_z or 0.1),
    "far_z: "        .. tostring(opts.far_z or 500.0),
    "auto_aspect_ratio: " .. (opts.auto_aspect_ratio == false and "0" or "1"),
    "orthographic_projection: " ..
      (opts.orthographic and "1" or "0"),
    "orthographic_zoom: " .. tostring(opts.orthographic_zoom or 1.0),
  }
  return table.concat(lines, "\n") .. "\n"
end

-- Build a camera_component spec compatible with gameobject._render_go_file.
local function _camera_component_spec(comp_id, opts)
  return {
    id = comp_id or "camera",
    type = "camera",
    data = {
      aspect_ratio = opts.aspect_ratio or 1.0,
      fov = opts.fov or 1.2566,
      near_z = opts.near_z or 0.1,
      far_z = opts.far_z or 500.0,
      auto_aspect_ratio = (opts.auto_aspect_ratio == false) and 0 or 1,
      orthographic_projection = opts.orthographic and 1 or 0,
      orthographic_zoom = opts.orthographic_zoom or 1.0,
    },
  }
end

-- ---------------------------------------------------------- preset bodies ----

-- A first-person / orbital third-person script: reads mouse motion messages
-- and updates the GO's yaw + pitch. Parent the camera GO under the target
-- in main.collection so position follows automatically.
local _ORBITAL_3D = [[
-- Generated by defold-ai camera_manage(apply_preset="follow_3d").
-- Parent this GO to your target instance in main.collection. The camera
-- inherits target position; this script only handles yaw/pitch orbit + the
-- back/up offset.

go.property("spring_len", 5.5)
go.property("height_offset", 1.6)
go.property("pitch_min", -1.2)
go.property("pitch_max",  0.6)

function init(self)
    msg.post("#camera", "acquire_camera_focus")
    self.yaw   = 0
    self.pitch = -0.35
end

local function apply(self)
    local q_yaw   = vmath.quat_rotation_y(self.yaw)
    local q_pitch = vmath.quat_rotation_x(self.pitch)
    local rot     = q_yaw * q_pitch
    local back    = vmath.rotate(rot, vmath.vector3(0, 0, self.spring_len))
    local pos     = vmath.vector3(0, self.height_offset, 0) + back
    go.set_position(pos)
    go.set_rotation(rot)
end

function update(self, dt)
    apply(self)
end

function on_message(self, message_id, message, sender)
    if message_id == hash("look") then
        local sens = message.sens or 0.0028
        self.yaw   = self.yaw   - (message.dx or 0) * sens
        self.pitch = self.pitch - (message.dy or 0) * sens
        if self.pitch < self.pitch_min then self.pitch = self.pitch_min end
        if self.pitch > self.pitch_max then self.pitch = self.pitch_max end
    end
end
]]

-- A 2D follow script: the camera GO smoothly tracks a target URL.
local _FOLLOW_2D = [[
-- Generated by defold-ai camera_manage(apply_preset="follow_2d").
-- Set the `target` property to a URL string ("/player") and the camera
-- will smoothly chase it every frame.

go.property("target", msg.url("/player"))
go.property("lerp", 0.18)

function init(self)
    msg.post("#camera", "acquire_camera_focus")
    local tp = go.get_position(self.target)
    go.set_position(vmath.vector3(tp.x, tp.y, go.get_position().z))
end

function update(self, dt)
    local tp  = go.get_position(self.target)
    local cur = go.get_position()
    local nx  = cur.x + (tp.x - cur.x) * self.lerp
    local ny  = cur.y + (tp.y - cur.y) * self.lerp
    go.set_position(vmath.vector3(nx, ny, cur.z))
end
]]

local PRESETS = {
  perspective_basic = {
    desc = "Plain perspective camera, no follow script. Position it manually.",
    overrides = { orthographic = false, fov = 1.2566 },
    script = nil,
  },
  orthographic_basic = {
    desc = "Plain orthographic camera, no follow script.",
    overrides = { orthographic = true, orthographic_zoom = 1.0 },
    script = nil,
  },
  follow_3d = {
    desc = "Third-person orbital. Parent the camera GO under your target.",
    overrides = { orthographic = false, fov = 1.2566, far_z = 500 },
    script = _ORBITAL_3D,
    properties = {  -- exposed go.property defaults for the generated script
      spring_len = 5.5, height_offset = 1.6,
      pitch_min = -1.2, pitch_max = 0.6,
    },
  },
  follow_2d = {
    desc = "2D camera that lerps to a target URL each frame.",
    overrides = { orthographic = true, orthographic_zoom = 1.0 },
    script = _FOLLOW_2D,
    properties = { lerp = 0.18 },
  },
}

local function _merge(base, overrides)
  if type(overrides) ~= "table" then return base end
  for k, v in pairs(overrides) do
    if type(v) == "table" and type(base[k]) == "table" then
      base[k] = _merge(base[k], v)
    else
      base[k] = v
    end
  end
  return base
end

-- ---------------------------------------------------------- public ops ----

function M.manage(body)
  local op = body.op or ""
  local params = body.params or {}

  if op == "list_presets" then
    local out = {}
    for k, v in pairs(PRESETS) do
      table.insert(out, { name = k, description = v.desc })
    end
    table.sort(out, function(a, b) return a.name < b.name end)
    return { ok = true, presets = out }

  elseif op == "create" then
    -- Just a camera.go with a camera component. No script. Use apply_preset
    -- for follow rigs.
    local path = util.norm_resource_path(params.path or "")
    if path == "" then return util.error_response("MISSING_PARAM", "create needs path") end
    if not path:match("%.go$") then path = path .. ".go" end
    local content = gameobject._render_go_file({
      _camera_component_spec("camera", params),
    })
    editor.create_resources({ { path, content } })
    return { ok = true, path = path }

  elseif op == "apply_preset" then
    local path = util.norm_resource_path(params.path or "")
    local preset_name = params.preset or ""
    if path == "" or preset_name == "" then
      return util.error_response("MISSING_PARAM", "apply_preset needs path + preset")
    end
    local preset = PRESETS[preset_name]
    if not preset then
      local names = {}
      for k, _ in pairs(PRESETS) do table.insert(names, k) end
      return util.error_response("UNKNOWN_PRESET",
        "preset '" .. preset_name .. "' unknown. Available: " ..
        table.concat(names, ", "))
    end
    if not path:match("%.go$") then path = path .. ".go" end

    -- Camera component opts: preset overrides + user overrides.
    local cam_opts = _merge({}, preset.overrides or {})
    cam_opts = _merge(cam_opts, params.camera or {})

    local components = { _camera_component_spec("camera", cam_opts) }
    local result = { ok = true, path = path, preset = preset_name }

    if preset.script then
      -- Generate a sibling .script with the preset's body.
      local script_path = path:gsub("%.go$", ".script")
      editor.create_resources({ { script_path, preset.script } })
      -- Reference it as the first component.
      table.insert(components, 1, {
        id = "script",
        component = script_path,
        properties = preset.properties,
      })
      result.script = script_path
    end

    local go_content = gameobject._render_go_file(components)
    editor.create_resources({ { path, go_content } })
    return result
  end
  return util.error_response("UNKNOWN_OP", "Unknown camera_manage op: " .. op)
end

return M
